stages:
  - deploy
  - verify

deploy_preview:
  stage: deploy
  image: node:latest
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN  --scope=$VERCEL_TEAM_SLUG
    # If under 15000 files use vercel build and then vercel deploy with --prebuilt
    # - vercel build --token=$VERCEL_TOKEN
    # - vercel deploy --prebuilt  --token=$VERCEL_TOKEN
    - echo "DEPLOYMENT_URL=$(vercel deploy --token=$VERCEL_TOKEN --scope=$VERCEL_TEAM_SLUG --yes) > deploy_url.txt"
    - echo "Deployment URL is $DEPLOYMENT_URL"
  artifacts:
    paths:
      - deploy_url.txt
    reports:
      dotenv: deploy.env

deploy_production:
  stage: deploy
  image: node:latest
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN  --scope=$VERCEL_TEAM_SLUG
    # If under 15000 files use vercel build and then vercel deploy with --prebuilt
    # - vercel build --prod --token=$VERCEL_TOKEN
    # - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
    - echo "DEPLOYMENT_URL=$(vercel deploy --token=$VERCEL_TOKEN --scope=$VERCEL_TEAM_SLUG --yes) > deploy_url.txt"
    - echo "Deployment URL is $DEPLOYMENT_URL"

verify_preview_deployment:
  stage: verify
  image: curlimages/curl:latest
  dependencies:
    - deploy_preview
  script:
    - source deploy_url.txt
    - 'curl --silent --show-error "$DEPLOYMENT_URL"'

verify_prod_deployment:
  stage: verify
  image: curlimages/curl:latest
  dependencies:
    - deploy_production
  script:
    - source deploy_url.txt
    - 'curl --silent --show-error "$DEPLOYMENT_URL"'
