default:
  image: node:latest

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    # If under 15000 files use --prebuilt
    # - vercel deploy --prebuilt  --token=$VERCEL_TOKEN
    - vercel deploy --token=$VERCEL_TOKEN --scope=$VERCEL_TEAM_SLUG

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
