/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ogUFC5zUUCM
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client';

import { useState } from 'react';
import { Switch } from '#/ui/ui/switch';
import { Label } from '#/ui/ui/label';

export function PreviewModeToggle() {
  const [isPreviewMode, setIsPreviewMode] = useState(false);
  const handleToggle = () => {
    setIsPreviewMode((prevState) => {
      const newState = !prevState;
      console.log(`Preview Mode ${newState ? 'on' : 'off'}`);
      return newState;
    });
  };
  return (
    <div className="flex items-center gap-2">
      <Switch
        id="preview-mode"
        checked={isPreviewMode}
        onCheckedChange={handleToggle}
      />
      <Label htmlFor="preview-mode">Preview Mode</Label>
    </div>
  );
}
