name: Change Tracking Marker

on:
  release:
    types: [published]
  # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
    inputs:
      name:
        description: 'What is your name'
        type: string
      home:
        description: 'WHere is your Home'
        type: string

jobs:
  newrelic:
    runs-on: ubuntu-latest
    name: New Relic
    steps:
      - name: Set Release Version from Tag
        run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: App123 Marker
        uses: newrelic/deployment-marker-action@v2.3.0
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
          version: '${{ env.RELEASE_VERSION }}'
          changelog: 'https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md'
          commit: '${{ github.sha }}'
          description: 'Automated Release via Github Actions'
          deploymentType: 'ROLLING'
          groupId: 'Workshop App Release: ${{ github.ref_name }}'
          user: '${{ github.actor }}'
      - name: App456 Marker
        uses: newrelic/deployment-marker-action@v2.3.0
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID_App456 }}
          version: '${{ env.RELEASE_VERSION }}'
          changelog: 'https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md'
          commit: '${{ github.sha }}'
          description: 'Automated Release via Github Actions'
          deploymentType: 'ROLLING'
          groupId: 'Workshop App Release: ${{ github.ref_name }}'
          user: '${{ github.actor }}'
