name: Change Tracking Marker
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  newrelic:
    runs-on: ubuntu-latest
    name: New Relic
    steps:
      # This step builds a var with the release tag value to use later
      - name: Set Release Version from Tag
        run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      # This step creates a new Change Tracking Marker for App123
      - name: App123 Marker
        uses: newrelic/deployment-marker-action@v2.3.0
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
          version: '${{ env.RELEASE_VERSION }}'
          changelog: 'https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md'
          commit: '${{ github.sha }}'
          description: 'Automated Release via Github Actions'
          deploymentType: 'ROLLING'
          groupId: 'Workshop App Release: ${{ github.ref_name }}'
          user: '${{ github.actor }}'
      # This step creates a new Change Tracking Marker for App456
      - name: App456 Marker
        uses: newrelic/deployment-marker-action@v2.3.0
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID_App456 }}
          version: '${{ env.RELEASE_VERSION }}'
          changelog: 'https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md'
          commit: '${{ github.sha }}'
          description: 'Automated Release via Github Actions'
          deploymentType: 'ROLLING'
          groupId: 'Workshop App Release: ${{ github.ref_name }}'
          user: '${{ github.actor }}'
